services:
  - type: web
    name: warzone-tournament-api
    env: node
    rootDir: project
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb+srv://chahbounibadr:siritna3si@cluster0.dfidjct.mongodb.net/warzone-tournaments?retryWrites=true&w=majority
      - key: FRONTEND_URL
        value: https://codesporttournament.netlify.app
      - key: SESSION_SECRET
        value: warzone-super-secret-key-2025-production
      - key: ADMIN_CODE_1
        value: MISOKIETI
      - key: ADMIN_CODE_2
        value: MISOKIETI8
      - key: LOG_LEVEL
        value: info
      - key: MAX_FILE_SIZE
        value: 50mb