services:
  - type: web
    name: warzone-tournament-api
    env: node
    rootDir: project
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: FRONTEND_URL
        value: https://codesporttournament.netlify.app
      - key: SESSION_SECRET
        sync: false
      - key: ADMIN_CODE_1
        sync: false
      - key: ADMIN_CODE_2
        sync: false
      - key: LOG_LEVEL
        value: info
      - key: MAX_FILE_SIZE
        value: 50mb